name: Daten abrufen und schreiben

on:
  workflow_run:
    workflows: ["Daten abrufen und schreiben"]
    types:
      - completed

permissions:
  contents: write

jobs:
  fetch-and-write-data:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Berlin

    steps:
    - name: Repository auschecken
      uses: actions/checkout@v3

    - name: Git konfigurieren
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"

    - name: Python einrichten
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Abhängigkeiten installieren
      run: pip install requests

    - name: Skript ausführen
      run: python fetch_data.py

    - name: Änderungen committen und pushen
      run: |
        git add data/
        timestamp=$(date "+%Y-%m-%d %H:%M:%S")
        git commit -m "Automatisches Update der Daten: $timestamp" || exit 0
        git push origin HEAD:main

    - name: 5 Minuten warten
      run: sleep 300
