name: Daten abrufen und schreiben

on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches:
      - main
    paths-ignore:
      - 'data/**'

jobs:
  fetch-and-write-data:
    runs-on: ubuntu-latest

    steps:
    - name: Repository auschecken
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Git konfigurieren
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"

    - name: Python einrichten
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Abhängigkeiten installieren
      run: pip install requests

    - name: Skript ausführen
      run: python your_script.py

    - name: Änderungen committen und pushen
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add data/
        timestamp=$(date -u "+%Y-%m-%d %H:%M:%S")
        git commit -m "Automatisches Update der Daten: $timestamp" || exit 0
        git push origin HEAD:main
